param([Parameter(Mandatory=$true)][string]$MetaTraderRoot,[Parameter(Mandatory=$true)][string]$RepoRoot,[double]$Deposit=10000.0,[string]$Leverage='1:100')
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$results=Join-Path $RepoRoot 'artifacts/architecture-g-baseline-5y';$compileDir=Join-Path $results 'compile';$frozenDir=Join-Path $results 'frozen_inputs';$diag=Join-Path $results 'diagnostics'
$source=Join-Path $RepoRoot 'mt5/PeakFX_EURUSD_ARCH_G_MTF_TREND_PULLBACK.mq5';$spec=Join-Path $RepoRoot 'docs/ARCHITECTURE_G_FROZEN_BASELINE_SPEC.md';$verifier=Join-Path $RepoRoot 'scripts/verify_architecture_g_artifact.py';$editor=Join-Path $MetaTraderRoot 'metaeditor64.exe';$terminal=Join-Path $MetaTraderRoot 'terminal64.exe'
foreach($p in @($source,$spec,$verifier,$editor,$terminal)){if(-not(Test-Path $p)){throw "Missing: $p"}}
if(Test-Path $results){Remove-Item $results -Recurse -Force};New-Item -ItemType Directory -Force -Path $results,$compileDir,$frozenDir,$diag|Out-Null
function Norm([string]$p){([IO.Path]::GetFullPath($p)).TrimEnd('\').ToLowerInvariant()}
function DataRoot(){ $base=Join-Path $env:APPDATA 'MetaQuotes\Terminal';$want=Norm $MetaTraderRoot;$m=@();foreach($r in Get-ChildItem $base -Directory){$o=Join-Path $r.FullName 'origin.txt';if(Test-Path $o){$t=(Get-Content $o -Raw).Trim();if($t -and (Norm $t)-eq$want){$m+=$r.FullName}}};if($m.Count-ne1){throw "Expected one MT5 data root; found $($m.Count)"};$m[0] }
function StopMt5{Get-Process terminal64,metatester64 -ErrorAction SilentlyContinue|Stop-Process -Force -ErrorAction SilentlyContinue;Start-Sleep 2}
function SetLine($n,$v){"$n=$v||$v||0||$v||N"}
function ReadText($p){$b=[IO.File]::ReadAllBytes($p);if($b.Length-ge2-and$b[0]-eq0xFF-and$b[1]-eq0xFE){[Text.Encoding]::Unicode.GetString($b)}else{[Text.Encoding]::UTF8.GetString($b)}}
function Num($t,$pat,$lab){$m=[regex]::Match($t,$pat,[Text.RegularExpressions.RegexOptions]::IgnoreCase);if(-not$m.Success){throw "Missing report field $lab"};[double]::Parse(($m.Groups[1].Value-replace'[^0-9.\-]',''),[Globalization.CultureInfo]::InvariantCulture)}
function AssertReport($p,$from,$to){$t=ReadText $p;$num='[0-9\s,\u00A0\u202F]+(?:\.[0-9]+)?';$int='[0-9\s,\u00A0\u202F]+';$dep=Num $t "Initial Deposit:\s*</td>\s*<td[^>]*><b>($num)" 'deposit';$bars=Num $t "Bars:\s*</td>\s*<td[^>]*><b>($int)" 'bars';$ticks=Num $t "Ticks:\s*</td>\s*<td[^>]*><b>($int)" 'ticks';if([math]::Abs($dep-$Deposit)-gt0.01-or$bars-le0-or$ticks-le0){throw 'Invalid backtest report'};if($t-notmatch[regex]::Escape($from)-or$t-notmatch[regex]::Escape($to)){throw 'Wrong report period'};[ordered]@{initial_deposit=$dep;bars=[long]$bars;ticks=[long]$ticks}}
$data=DataRoot;$experts=Join-Path $data 'MQL5\Experts\PeakFX';$profiles=Join-Path $data 'MQL5\Profiles\Tester';New-Item -ItemType Directory -Force -Path $experts,$profiles|Out-Null
$depSrc=Join-Path $experts ([IO.Path]::GetFileName($source));Copy-Item $source $depSrc -Force;$cl=Join-Path $compileDir 'meta_compiler.log';Start-Process $editor -ArgumentList @("/compile:`"$depSrc`"","/log:`"$cl`"") -Wait|Out-Null;$ct=Get-Content $cl -Raw;if($ct-notmatch'(?i)\b0\s+errors?\s*,\s*0\s+warnings?\b'){throw 'Compile failed'};$bin=[IO.Path]::ChangeExtension($depSrc,'.ex5');if(-not(Test-Path $bin)){throw 'Binary missing'}
$sh=(Get-FileHash $source -Algorithm SHA256).Hash.ToLowerInvariant();$bh=(Get-FileHash $bin -Algorithm SHA256).Hash.ToLowerInvariant();$sph=(Get-FileHash $spec -Algorithm SHA256).Hash.ToLowerInvariant();Copy-Item $source,$bin,$spec,$verifier -Destination $frozenDir -Force
$configs=@(@{id='G01';sep='0.10';target='1.25'},@{id='G02';sep='0.20';target='1.25'},@{id='G03';sep='0.10';target='1.75'},@{id='G04';sep='0.20';target='1.75'});$wins=@(@{id='2020_2021';f='2020.07.01';t='2021.06.30'},@{id='2021_2022';f='2021.07.01';t='2022.06.30'},@{id='2022_2023';f='2022.07.01';t='2023.06.30'},@{id='2023_2024';f='2023.07.01';t='2024.06.30'},@{id='2024_2025';f='2024.07.01';t='2025.06.30'})
$lev=[int]($Leverage.Split(':')[1]);$runs=@()
foreach($c in $configs){$sn="architecture_g_$($c.id.ToLower()).set";$sp=Join-Path $profiles $sn;$lines=@('InpSymbol=EURUSD',(SetLine 'InpRiskPercent' '0.25'),(SetLine 'InpDailyLossLimitPercent' '1.0'),(SetLine 'InpWeeklyLossLimitPercent' '2.0'),(SetLine 'InpH4SeparationAtr' $c.sep),(SetLine 'InpTargetR' $c.target),(SetLine 'InpStopAtrBuffer' '0.25'),(SetLine 'InpMaxSpreadPips' '2.0'),(SetLine 'InpDeviationPoints' '10'),(SetLine 'InpMagic' '26080707'));Set-Content $sp (($lines-join"`r`n")+"`r`n") -Encoding Unicode;$seth=(Get-FileHash $sp -Algorithm SHA256).Hash.ToLowerInvariant();Copy-Item $sp (Join-Path $frozenDir $sn) -Force
foreach($w in $wins){$stage=Join-Path $results "$($c.id)\$($w.id)";New-Item -ItemType Directory -Force -Path $stage|Out-Null;$stem="arch_g_$($c.id.ToLower())_$($w.id)_report";$ini=Join-Path $stage "$stem.ini";$txt="[Tester]`r`nExpert=PeakFX\PeakFX_EURUSD_ARCH_G_MTF_TREND_PULLBACK.ex5`r`nExpertParameters=$sn`r`nSymbol=EURUSD`r`nPeriod=H1`r`nModel=4`r`nExecutionMode=0`r`nOptimization=0`r`nFromDate=$($w.f)`r`nToDate=$($w.t)`r`nForwardMode=0`r`nDeposit=$Deposit`r`nCurrency=USD`r`nLeverage=$lev`r`nReport=$stem`r`nReplaceReport=1`r`nShutdownTerminal=1`r`nVisual=0`r`n";Set-Content $ini $txt -Encoding ASCII;StopMt5;$started=Get-Date;Write-Host "Running $($c.id)/$($w.id)";Start-Process $terminal -WorkingDirectory $MetaTraderRoot -ArgumentList "/config:`"$ini`"" -Wait|Out-Null;$roots=@($stage,$data,$MetaTraderRoot,(Join-Path $env:APPDATA 'MetaQuotes\Terminal\Common'));$found=$null;foreach($root in $roots){if(Test-Path $root){$x=Get-ChildItem $root -File -Recurse -ErrorAction SilentlyContinue|Where-Object{$_.BaseName-eq$stem-and@('.htm','.html','.xml')-contains$_.Extension.ToLowerInvariant()-and$_.LastWriteTime-ge$started.AddMinutes(-1)}|Sort-Object LastWriteTime -Descending|Select-Object -First 1;if($x){$found=$x;break}}};if(-not$found){throw "No report $($c.id)/$($w.id)"};$rp=Join-Path $stage $found.Name;if($found.FullName-ine$rp){Copy-Item $found.FullName $rp -Force};$ex=AssertReport $rp $w.f $w.t;$rh=(Get-FileHash $rp -Algorithm SHA256).Hash.ToLowerInvariant();$m=[ordered]@{architecture='G';configuration=$c.id;window=$w.id;start=$w.f;end=$w.t;h4_separation_atr=[double]$c.sep;target_r=[double]$c.target;parameter_set=$sn;parameter_set_sha256=$seth;spec_sha256=$sph;source_sha256=$sh;binary_sha256=$bh;report=$rp;report_sha256=$rh;model='real_ticks';symbol='EURUSD';timeframe='H1';deposit=$Deposit;leverage=$Leverage;oos_locked=$true;execution=$ex};$m|ConvertTo-Json -Depth 6|Set-Content (Join-Path $stage 'run_metadata.json') -Encoding UTF8;$runs+=$m}}
if($runs.Count-ne20){throw "Expected 20 runs, got $($runs.Count)"};[ordered]@{protocol='Architecture G frozen baseline';expected_run_count=20;completed_run_count=$runs.Count;source_sha256=$sh;binary_sha256=$bh;spec_sha256=$sph;runs=$runs;oos_locked=$true;reserved_oos_not_tested=$true;generated_at=(Get-Date).ToString('o')}|ConvertTo-Json -Depth 9|Set-Content (Join-Path $results 'architecture_g_manifest.json') -Encoding UTF8;Write-Host 'Architecture G baseline complete: 20 reports.'
